"""
360SCOUT — Asian Handicap Engine (The Winning Method — Safe Match shift)

Problem: a heavy 1X2 favourite (decimal odds ~1.15-1.45) has almost no value
on the straight win — the market has already priced in the near-certainty.
But if the Poisson model gives that favourite a real chance to win by 2+
goals, the mispriced value has simply moved markets: from "will they win"
(already efficient) to "by how much" (often softer, thinner-liquidity line).

This reuses goals_engine's xG calibration + Poisson matrix (same inputs that
drive the Over/Under Winning Method) and asks a different question of the
same matrix: not total goals, but winning margin.
"""

from __future__ import annotations

import dataclasses
from dataclasses import dataclass
from typing import Literal

import numpy as np

from app.engine.goals_engine import XgModifiers, adjust_xg, _poisson_matrix

# ── "Safe Match + High Margin" trigger thresholds ─────────────────────────────
SAFE_MATCH_ODDS_MIN = 1.15          # shorter than this isn't "safe", it's a lock — different problem
SAFE_MATCH_ODDS_MAX = 1.45          # longer than this and the straight win still has value on its own
HIGH_MARGIN_PROB_THRESHOLD = 0.50   # "high probability" = model favours a 2+ goal margin outright

AH_LINE: float = -1.5


def _ah_rating(edge_pct: float) -> str:
    if edge_pct >= 25.0: return "STRONG"
    if edge_pct >= 15.0: return "MODERATE"
    if edge_pct >= 5.0:  return "WEAK"
    return "NONE"


@dataclass(frozen=True)
class HandicapValueSignal:
    """Immutable result of a Safe-Match Asian Handicap check. Generated by calculate_handicap_value()."""
    triggered:      bool     # both trigger conditions met -> shift recommendation from straight win to AH

    favorite:       Literal["home", "away"]
    favorite_team:  str
    underdog_team:  str
    line:           float    # always -1.5 for this signal

    xg_home:        float
    xg_away:        float

    cover_prob:     float          # P(favourite wins by 2+) — 0-1
    straight_win_prob: float       # P(favourite wins straight, any margin) — 0-1
    straight_odds:  float          # market 1X2 odds for the favourite
    straight_edge:  float          # EV% on the straight win at those odds

    ah_odds:        float | None   # real market -1.5 odds, when the book offers that exact line
    ah_fair_odds:   float          # model's fair price = 1 / cover_prob
    ah_edge:        float | None   # EV% vs ah_odds — None when no market line was found
    ah_rating:      str            # STRONG/MODERATE/WEAK/NONE — NONE whenever ah_odds is None
    bookmaker:      str | None     # source of ah_odds, when present

    is_safe_match:  bool
    is_high_margin: bool

    reasoning:      str             # 2-sentence Hebrew justification (xG + margin probability)
    modifiers_applied: tuple

    def to_dict(self) -> dict:
        d = dataclasses.asdict(self)
        d["modifiers_applied"] = list(d["modifiers_applied"])
        return d


def calculate_handicap_value(
    xg_home:        float,
    xg_away:        float,
    favorite:       Literal["home", "away"],
    favorite_team:  str,
    underdog_team:  str,
    straight_odds:  float,
    ah_odds:        float | None = None,
    bookmaker:      str | None = None,
    mods:           XgModifiers | None = None,
    max_goals:      int = 5,
) -> HandicapValueSignal | None:
    """
    'Safe Match + High Margin' — The Winning Method's Asian Handicap shift.

    Returns None when straight_odds isn't in the 1.15-1.45 "Safe Match" window
    at all (this isn't a candidate for the shift, whatever the margin says) or
    when inputs are invalid. When it returns a signal, check `.triggered` —
    True only when the margin probability also clears HIGH_MARGIN_PROB_THRESHOLD.

    ah_odds: real market -1.5 price for the favourite, when available (e.g. from
    The Odds API's spreads market). When None, ah_edge/ah_rating stay unset and
    only the model's fair price (ah_fair_odds) is reported.
    """
    if straight_odds <= 1.0 or xg_home <= 0 or xg_away <= 0:
        return None

    is_safe_match = SAFE_MATCH_ODDS_MIN <= straight_odds <= SAFE_MATCH_ODDS_MAX
    if not is_safe_match:
        return None

    axg = adjust_xg(xg_home, xg_away, mods)
    lh  = max(axg.xg_home, 0.05)
    la  = max(axg.xg_away, 0.05)

    matrix = _poisson_matrix(lh, la, max_goals)
    ks     = np.arange(max_goals + 1)
    diff   = ks[:, None] - ks[None, :]   # home goals − away goals, per matrix cell

    if favorite == "home":
        cover_prob = float(matrix[diff >= 2].sum())
        straight_win_prob = float(np.tril(matrix, -1).sum())
    else:
        cover_prob = float(matrix[diff <= -2].sum())
        straight_win_prob = float(np.triu(matrix, 1).sum())

    is_high_margin = cover_prob >= HIGH_MARGIN_PROB_THRESHOLD
    triggered      = is_safe_match and is_high_margin

    straight_edge = round((straight_win_prob * straight_odds - 1) * 100, 2)
    ah_fair_odds  = round(1 / max(cover_prob, 0.0001), 2)

    ah_edge   = None
    ah_rating = "NONE"
    if ah_odds and ah_odds > 1.0:
        ah_edge   = round((cover_prob * ah_odds - 1) * 100, 2)
        ah_rating = _ah_rating(ah_edge)

    fav_he      = "הבית" if favorite == "home" else "האורחים"
    margin_line = f"{AH_LINE:g}"
    reasoning = (
        f"{favorite_team} פייבוריט ברור ביחס {straight_odds:.2f}, אך זהו ערך נמוך על ניצחון ישיר בלבד — "
        f"מודל פואסון (xG מכויל {axg.xg_home:.2f}–{axg.xg_away:.2f}) נותן ל{fav_he} "
        f"{cover_prob * 100:.0f}% לנצח בפער של 2+ שערים. "
        f"קו אסיאן הנדיקאפ {margin_line} הופך את אותה דומיננטיות ליתרון מתמטי אמיתי, "
        f"במקום לתשואה זעומה של {straight_edge:+.1f}% על ה-1X2."
    )

    return HandicapValueSignal(
        triggered       = triggered,
        favorite        = favorite,
        favorite_team   = favorite_team,
        underdog_team   = underdog_team,
        line            = AH_LINE,
        xg_home         = axg.xg_home,
        xg_away         = axg.xg_away,
        cover_prob      = round(cover_prob, 4),
        straight_win_prob = round(straight_win_prob, 4),
        straight_odds   = straight_odds,
        straight_edge   = straight_edge,
        ah_odds         = ah_odds,
        ah_fair_odds    = ah_fair_odds,
        ah_edge         = ah_edge,
        ah_rating       = ah_rating,
        bookmaker       = bookmaker,
        is_safe_match   = is_safe_match,
        is_high_margin  = is_high_margin,
        reasoning       = reasoning,
        modifiers_applied = axg.modifiers_applied,
    )
